### ISSUE TITLE
Automate database backup.

### ISSUE THREAD

**Issue by BuckinghamIO** [SebastianUA/terraform#1]
Not so much of a bug but a question around the GCP Postgres database.

Have you come across a way to automatically restore a backup within GCP to a newly created database instance via Terraform.  AWS has this feature using the snapshot object, and I've been trying to replicate it in GCP with no success.

**Comment by SebastianUA** [comment]
Hi @BuckinghamIO, 
I think, the best way is to use snapshot for restoring some data.
If you have any issues, you could post them to Terraform - https://github.com/hashicorp/terraform/issues

Could you please share additional info/output of your `terraform plan` and `terraform apply`?
I will try to help you ;)

PS: Please use https://gist.github.com/ to share any outputs with me.

Cheers,
Vitaliy
