### ISSUE TITLE
Azure Storage Module

### ISSUE THREAD

**Issue by lefig** [SebastianUA/terraform#12]
Hi Sebastian,

Firstly a fabulous project and what must be the most comprehensive library of modules that I have seen for the Terraform.

Regarding the Storage module on Azure I am running the example but seem to have a dynamic problem. 

│ Error: Unsupported argument
│
│   on ..\terraform\azure\modules\storage\storage_sync_group.tf line 17, in resource "azurerm_storage_sync_group" "storage_sync_group":
│   17:       update = lookup(timeouts.value, "update", null)
│
│ An argument named "update" is not expected here.

And various...

 on ..\terraform\azure\modules\storage\storage_account.tf line 237, in resource "azurerm_storage_account" "storage_account":
│  237:     for_each = length(keys(var.storage_account_azure_files_authentication)) > 0 ? [var.storage_account_azure_files_authentication] : []
│
│ There is no variable named "var".

I have checked the versions that I use but am still stumped.

Thanks for any thoughts that you may have and for a great work.

Fig

**Comment by SebastianUA** [comment]
Hi @lefig 

Thank you very much for reporting. I just fix one issue and you can get the changes from https://github.com/SebastianUA/terraform/tree/dev

Regarding the second one, please check the structure of the variable: ```storage_account_azure_files_authentication = {
    directory_type = ""

    active_directory = {
        storage_sid           = null
          domain_name         = null
          domain_sid          = null
          domain_guid         = null
          forest_name         = null
          netbios_domain_name = null
    }
}```

Also, could you please share your executing TF code with me to understand your case and help you?
Thanks

**Comment by lefig** [comment]
Hi @SebastianUA ,

A big thank you for taking a look at this (the Storage module). I have checked the dev branch out but see some duplicate variable errors:

# variable "storage_sync_group_timeouts" {
#   description = "Set timeouts for storage sync group"
#   default     = {}
# }

and in Outputs.tf:
# output "storage_share_directory_id" {
#   description = "The ID of the Directory within the File Share."
#   value       = element(concat(azurerm_storage_share_directory.storage_share_directory.*.id, [""]), 0)
# }

Then on Plan the following same errors:

Error: Unsupported argument
│
│   on ..\modules\storage\storage_account.tf line 14, in resource "azurerm_storage_account" "storage_account":
│   14:   cross_tenant_replication_enabled  = var.storage_account_cross_tenant_replication_enabled
│
│ An argument named "cross_tenant_replication_enabled" is not expected     
│ here.
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 30, in resource "azurerm_storage_account" "storage_account":
│   30:     for_each = length(keys(var.storage_account_custom_domain)) > 0 
? [var.storage_account_custom_domain] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 41, in resource "azurerm_storage_account" "storage_account":
│   41:     for_each = length(keys(var.storage_account_customer_managed_key)) > 0 ? [var.storage_account_customer_managed_key] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 51, in resource "azurerm_storage_account" "storage_account":
│   51:     for_each = length(keys(var.storage_account_identity)) > 0 ? [var.storage_account_identity] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 62, in resource "azurerm_storage_account" "storage_account":
│   62:     for_each = length(keys(var.storage_account_blob_properties)) > 
0 ? [var.storage_account_blob_properties] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 106, in resource "azurerm_storage_account" "storage_account":
│  106:     for_each = length(keys(var.storage_account_queue_properties)) > 0 ? [var.storage_account_queue_properties] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 166, in resource "azurerm_storage_account" "storage_account":
│  166:     for_each = length(keys(var.storage_account_static_website)) > 0 ? [var.storage_account_static_website] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 176, in resource "azurerm_storage_account" "storage_account":
│  176:     for_each = length(keys(var.storage_account_share_properties)) > 0 ? [var.storage_account_share_properties] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Reference to undeclared resource
│
│   on ..\modules\storage\storage_account.tf line 194, in resource "azurerm_storage_account" "storage_account":
│  194:         for_each = length(keys(lookup(blob_properties.value, "retention_policy", {}))) > 0 ? [lookup(blob_properties.value, "retention_policy", {})] : []
│
│ A managed resource "blob_properties" "value" has not been declared in    
│ module.storage_account.
╵
╷
│ Error: Reference to undeclared resource
│
│   on ..\modules\storage\storage_account.tf line 194, in resource "azurerm_storage_account" "storage_account":
│  194:         for_each = length(keys(lookup(blob_properties.value, "retention_policy", {}))) > 0 ? [lookup(blob_properties.value, "retention_policy", {})] : []
│
│ A managed resource "blob_properties" "value" has not been declared in    
│ module.storage_account.
╵
╷
│ Error: Reference to undeclared resource
│
│   on ..\modules\storage\storage_account.tf line 203, in resource "azurerm_storage_account" "storage_account":
│  203:         for_each = length(keys(lookup(blob_properties.value, "smb", {}))) > 0 ? [lookup(blob_properties.value, "smb", {})] : []
│
│ A managed resource "blob_properties" "value" has not been declared in    
│ module.storage_account.
╵
╷
│ Error: Reference to undeclared resource
│
│   on ..\modules\storage\storage_account.tf line 203, in resource "azurerm_storage_account" "storage_account":
│  203:         for_each = length(keys(lookup(blob_properties.value, "smb", {}))) > 0 ? [lookup(blob_properties.value, "smb", {})] : []
│
│ A managed resource "blob_properties" "value" has not been declared in    
│ module.storage_account.
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 217, in resource "azurerm_storage_account" "storage_account":
│  217:     for_each = length(keys(var.storage_account_network_rules)) > 0 
? [var.storage_account_network_rules] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 231, in resource "azurerm_storage_account" "storage_account":
│  231:     for_each = length(keys(var.storage_account_azure_files_authentication)) > 0 ? [var.storage_account_azure_files_authentication] : []       
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 254, in resource "azurerm_storage_account" "storage_account":
│  254:     for_each = length(keys(var.storage_account_routing)) > 0 ? [var.storage_account_routing] : []
│
│ There is no variable named "var".
╵
╷
│ Error: Unknown variable
│
│   on ..\modules\storage\storage_account.tf line 265, in resource "azurerm_storage_account" "storage_account":
│  265:     for_each = length(keys(var.storage_account_timeouts)) > 0 ? [var.storage_account_timeouts] : []
│
│ There is no variable named "var".

My usage of the module is simple:

module "base_resource_group" {
  source = "../modules/base"

  enable_resource_group   = true
  resource_group_name     = "res-group"
  resource_group_location = "West Europe"

  tags = tomap({
    "Environment"   = "test",
    "Createdby"     = "fig",
    "Orchestration" = "Terraform"
  })
}

module "storage_account" {
  source = "../modules/storage"

  // Enable storage account
  enable_storage_account = true

  storage_account_name                     = "aks-storage-account"
  storage_account_location                 = module.base_resource_group.resource_group_location
  storage_account_resource_group_name      = module.base_resource_group.resource_group_name
  storage_account_account_tier             = "Standard"
  storage_account_account_replication_type = "GRS"

  // Enable storage account network rules
  enable_storage_account_network_rules         = true
  storage_account_network_rules_default_action = "Allow"

  storage_account_network_rules_bypass                     = ["Metrics"]
  storage_account_network_rules_ip_rules                   = ["127.0.0.1"]
  storage_account_network_rules_virtual_network_subnet_ids = []

  // Enable storage account customer managed key
  enable_storage_account_customer_managed_key       = false
  storage_account_customer_managed_key_key_vault_id = ""
  storage_account_customer_managed_key_key_name     = ""

  tags = tomap({
    "Environment"   = "test",
    "Createdby"     = "fig",
    "Orchestration" = "Terraform"
  })

  depends_on = [
    module.base_resource_group
  ]
}

I wish I had better knowledge of TF but hopefully you may be able to take a look.

Thank you

Fig

**Comment by SebastianUA** [comment]
Hey @lefig 

Thank you! I just fixed duplicates. Going to check your TF code on my local env. I will let you know the updates.

**Comment by SebastianUA** [comment]
Hi @lefig 

I think I fixed the issues. Maybe you will have other ones, but it looks to work for now.  
The `azurerm` has bugs, for example here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account

Please `star` my projects if you really like them! :)
Thank you!

**Comment by lefig** [comment]
Hi @SebastianUA 

Fabulous work and the changes seem to do the trick:)

Yes, this is well worth the effort because TF is not easy and your library of modules are great resources to learn.

Keep up the good work please.

Fig
