### ISSUE TITLE
Azure Container Registry - ACR

### ISSUE THREAD

**Issue by lefig** [SebastianUA/terraform#16]
Hi Sebastian,

I hope that you don't mind me checking regarding whether ACR is supported.

I looked through the examples but don't seem to be able to locate.

It would be great to have this module implemented as a new feature if possible.

Thanks:)

Fig

**Comment by SebastianUA** [comment]
Hi @lefig 

I have checked that Azure supports those functionalities through TF. When I have time, I will add new additional features/modules/fixes and publish them.

Thank you very much for your comment and understanding.

--Vitalii
