### ISSUE TITLE
alb

### ISSUE THREAD

**Issue by safetylab** [SebastianUA/terraform#5]
Не создает таргеты в алб

**Comment by SebastianUA** [comment]
@safetylab, Спасибо что сказал. На днях, переделаю немного модуль, т.к он давно не обновлялся. 
Но я тестирую работу модулей, странно что не создает.

**Comment by SebastianUA** [comment]
@safetylab, Я переделал модуль и запушил код в `dev` бранч.

Пример работы модуля можно взять - https://github.com/SebastianUA/terraform/blob/dev/aws/examples/alb/main.tf
Модуль лежит пока тут - https://github.com/SebastianUA/terraform/tree/dev/aws/modules/alb

Можешь потестировать его и сказать что не хватает или что стоит добавить.
Спасибо!

**Comment by safetylab** [comment]
я уже просто апи использую - вопрос как provision засунуть в module ec2 - я хочу сделать запуск ансибла при деплое инстанса - примера найти не могу
